name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get emsdk |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - uses: actions/checkout@v1
    - name: 
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        BUILD_SCRIPT: mkdir build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=../emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake
